services:
  - type: web
    name: venus-jewel-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "waitress-serve --host=0.0.0.0 --port=$PORT app:app"
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        sync: false
      - key: SHEET_ID
        value: 19c2tlUmzSQsQhqNvWRuKMgdw86M0PLsKrWk51m7apA4
      - key: GOOGLE_DRIVE_FOLDER
        value: 1Yjvp5TMg7mERWxq4dsYJq748CcQIucLK
      - key: GOOGLE_CREDENTIALS_FILE
        value: /etc/secrets/credentials.json
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: Admin@2211
    secretFiles:
      - path: /etc/secrets/credentials.json
        envVarName: GOOGLE_CREDENTIALS_FILE


